baseURL = 'https://zstg.github.io/'
languageCode = 'en-us'
paginatePath = "page"
showMenuItems = 0
theme = "terminal"
[params]
  themeColor = "blue"
  # fullWidthTheme = true
  centerTheme = true
  
[params.logo]
   logoText = "Stig's blog"
   logoHomeLink = "/"
